---
- set_fact:
    _ports: "{{ rs_firewall.ports | default({}) }}"
    _services: "{{ rs_firewall.services | default({}) }}"

- set_fact:
    _enabled_services: "{{ _services.enabled | default([]) | union(rs_firewall_defaults.services.enabled) }}"

- set_fact:
    _enabled_services: "{{ _enabled_services | union(['mdns']) }}"
  when: "{{ ansible_local.deploy_env == 'vagrant' }}"

- set_fact:
    _disabled_services: "{{ _services.disabled | default([]) | union(rs_firewall_defaults.services.disabled) | difference(_enabled_services) }}"
    _open_ports: "{{ _ports.open | default([]) | union(rs_firewall_defaults.ports.open) }}"
    _closed_ports: "{{ _ports.closed | default([]) | difference(rs_firewall_defaults.ports.open) }}"

- name: configure firewall enabled services
  firewalld:
    immediate: yes
    permanent: yes
    service: "{{ item }}"
    state: enabled
  with_items: "{{ _enabled_services }}"

- name: configure firewall disabled services
  firewalld:
    immediate: yes
    permanent: yes
    service: "{{ item }}"
    state: disabled
  with_items: "{{ _disabled_services }}"

- name: configure firewall open ports
  firewalld:
    immediate: yes
    permanent: yes
    port: "{{ item }}"
    state: enabled
  with_items: "{{ _open_ports }}"

- name: configure firewall closed ports
  firewalld:
    immediate: yes
    permanent: yes
    port: "{{ item }}"
    state: disabled
  with_items: "{{ _closed_ports }}"
