---
- name: enable firewalld service
  systemd: name=firewalld.service daemon_reload=no enabled=yes state=started

- set_fact:
    fw_enabled_services: "{{ rs_firewall.services.enabled | union(rs_firewall.defaults.services.enabled) }}"
    
- set_fact:
    fw_disabled_services: "{{ rs_firewall.services.disabled | union(rs_firewall.defaults.services.disabled) | difference(fw_enabled_services) }}"

- name: configure firewall enabled services
  firewalld:
    permanent: yes
    service: "{{ item }}"
    state: enabled
  with_items: "{{ fw_enabled_services }}"

- name: configure firewall disabled services
  firewalld:
    permanent: yes
    service: "{{ item }}"
    state: disabled
  with_items: "{{ fw_disabled_services }}"

- name: mdns firewall rules
  firewalld:
    permanent: yes
    service: mdns
    state: enabled
  when: "{{ ansible_local.deploy_env == 'vagrant' }}"

