---
- name: firewalld is installed
  package: name=firewalld state=present

- name: enable firewalld service
  systemd: name=firewalld.service daemon_reload=no enabled=yes state=started

- set_fact:
    fw_enabled_services: "{{ rs_firewall.services.enabled | union(rs_firewall.defaults.services.enabled) }}"
   
- set_fact:
    fw_enabled_services: "{{ fw_enabled_services | union(['mdns']) }}"
  when: "{{ ansible_local.deploy_env == 'vagrant' }}"

- set_fact:
    fw_disabled_services: "{{ rs_firewall.services.disabled | union(rs_firewall.defaults.services.disabled) | difference(fw_enabled_services) }}"
    fw_open_ports: "{{ rs_firewall.ports.open | union(rs_firewall.defaults.ports.open) }}"
    fw_closed_ports: "{{ rs_firewall.ports.closed | difference(rs_firewall.defaults.ports.open) }}"

- name: configure firewall enabled services
  firewalld:
    immediate: yes
    permanent: yes
    service: "{{ item }}"
    state: enabled
  with_items: "{{ fw_enabled_services }}"

- name: configure firewall disabled services
  firewalld:
    immediate: yes
    permanent: yes
    service: "{{ item }}"
    state: disabled
  with_items: "{{ fw_disabled_services }}"

- name: configure firewall open ports
  firewalld:
    immediate: yes
    permanent: yes
    port: "{{ item }}"
    state: enabled
  with_items: "{{ fw_open_ports }}"

- name: configure firewall closed ports
  firewalld:
    immediate: yes
    permanent: yes
    port: "{{ item }}"
    state: disabled
  with_items: "{{ fw_closed_ports }}"
