---
- name: install nfs packages
  package: name={{ item }} state=installed
  with_items:
    - nfs-utils
    - rpcbind

- name: add file systems
  args:
    creates: "{{ nfs_export_prefix }}"
    executable: /bin/bash
  shell: |
    set -e
    mkdir -p '{{ nfs_export_prefix }}'
    chmod 755 '{{ nfs_export_prefix }}'
    echo y | mkfs -t ext4 '{{ nfs_block_device }}'
    echo '{{ nfs_block_device }} {{ nfs_export_prefix }} ext4 defaults 0 0' >> /etc/fstab
    chmod 755 '{{ nfs_export_prefix }}'
    mount '{{ nfs_export_prefix }}'
  when: nfs_block_device is defined

- name: enable nfs services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - rpcbind
    - nfs-server

- include: manage_export.yml
  with_dict: '{{ nfs_exports }}'
  loop_control:
    loop_var: export
