---
- name: install nfs packages
  package: name={{ item }} state=installed
  with_items:
    - nfs-utils
    - rpcbind  

- name: enable nfs services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - rpcbind
    - nfs-server

- include: manage_export.yml
  with_dict: '{{ nfs_exports }}'
  loop_control: 
    loop_var: export
