---
- name: create exported filesystems
  file: path={{ nfs_export_prefix }}/{{ export.key }}/{{ item.name }} state=directory
  with_items: '{{ export.value }}'

- name: generate exports file
  template: src=exports.j2 dest=/etc/exports.d/{{ export.key }}.exports owner=root group=root mode=0644
  notify: 'exports changed'
