---
- name: pull docker image {{ container.value.image_name }}
  docker_image: name={{ container.value.image_name }}

- set_fact:
    _volumes: "{{ container.value.volumes | default([]) }}"

- set_fact:
    _volumes: "{{ _volumes + ['{{docker_sock_path}}:{{docker_sock_path}}'] }}"
  when: "{{ radia_containers.want_docker_sock }}"

- name: create docker container
  docker_container:
    command: "{{ container.value.command | default(omit) }}"
    env: "{{ container.value.env | default(omit) }}"
    image: "{{ container.value.image_name }}"
    name: "{{ container.key }}"
    published_ports: "{{ container.value.ports | default(omit) }}"
    state: "{{ container.value.state | default(omit) }}"
    user: "{{ container.value.user | default(omit) }}"
    volumes: "{{ _volumes }}"

- block:
    - name: install systemd service for {{ container.value.image_name }}
      template: 
        src: templates/systemd_service.j2
        dest: '/etc/systemd/system/{{ container.key }}.service'
        owner: root
        group: root
        mode: 0644
      register: docker_service_installed

    - name: start systemd service for {{ container.value.image_name }}
      systemd:
        name: "{{ container.key }}.service"
        daemon_reload: yes
        state: "{{ container.value.service_state }}"
        enabled: "{{ container.value.on_boot }}"
      when: docker_service_installed|changed
  when: "{{ docker_systemd_service and container.value.state|default('present') == 'present' }}"
