---
- name: ssl private permissions
  file: path={{ ssl_storage.private }} state=directory owner=root group=root mode=0750

- name: copy radia start ssl certs
  copy: 
    src: "{{ ssl_radia_star }}.{{ item.ext }}"
    dest: "{{ item.path }}/{{ ssl_radia_star }}.{{ item.ext }}" 
    owner: root 
    group: root 
    mode: 0640
  with_items:
    - { path: "{{ ssl_storage.certs }}", ext: crt }
    - { path: "{{ ssl_storage.private }}", ext: key }
