---
- name: ssl private permissions
  file: path={{ ssl_storage.private }} state=file owner=root group=root mode=0750

- name: copy radia start ssl certs
  copy: 
    dest: "{{ item.path }}" 
    group: root 
    mode: 0640
    owner: root 
    src: "star.radiasoft.org.{{ item.ext }}"
  with_items:
    - { path: "{{ ssl_storage.certs }}", ext: crt }
    - { path: "{{ ssl_storage.private }}", ext: key }
  when: ansible_local.deploy_env != 'vagrant'
