---
- name: install hard requirements for ansible
  hosts: jenkins
  gather_facts: false
  roles:
    - bootstrap

- hosts: jenkins
  pre_tasks:
    - hostname: name=jenkins
    # TODO: There is an ordering an implicit circular dependency between the nginx and ssl roles; where the ssl role
    # depends on the nginx user being available and the nginx module requires the ssl keys existing. By installing nginx
    # and creating the user, we break the circular dependency. Is there a more elegant way?
    - dnf: name=nginx state=present   

    - group: name=ssl state=present system=yes

    - user: name=nginx append=yes state=present groups=ssl
    
  roles:
    - utilities
    - jenkins
