---
- hosts: all
  roles:
    - rs_base

- hosts: nfs
  roles:
    - nfs_server

- hosts: jupyterhub

  pre_tasks:
    - name: jupyterhub configuration directory
      file: 
        group: root
        mode: 0640
        owner: root
        path: '{{ jupyterhub.host.conf_d }}'
        state: directory

    - name: write jupyterhub configuration
      template:
        dest: '{{ jupyterhub.host.conf_d }}/jupyterhub_config.py'
        group: 0640
        owner: root
        src: templates/jupyterhub/jupyterhub_config.py.jinja
      register: jupyterhub_config

  roles:
    - nfs_client
    - rs_containers
    
  tasks:
    - name: restart jupyterhub service
      systemd: name=jupyterhub.service state=restarted
      when: jupyterhub_config|changed
