---
- hosts: nfs
  vars_files:
    - vars/jupyterhub/nfs_exports.yml
  roles:
    - nfs_server

- hosts: jupyterhub
  vars_files:
    - vars/jupyterhub/nfs_exports.yml
  roles:
    - radia_base
    - role: nfs_client
      nfs_host: radia-nfs.local
      imports:
        - jupyterhub
