---
- name: install hard requirements for ansible
  hosts: all
  remote_user: root
  roles:
    - bootstrap
  gather_facts: false

- name: setup host machine 
  hosts: all
  remote_user: root
  roles:
    - utilities

- hosts: jenkins
  remote_user: root
  vars_files:
    - vars/jenkins/plugins.yml
  pre_tasks:
    - hostname: name=jenkins
  roles:
    - avahi
    - role: jenkins
      jenkins_admin_password: 12345

- hosts: robhome 
  remote_user: root
  roles: 
  - utilities
  - sonos   
