---
jenkins_plugins:
  - ace-editor
  - antisamy-markup-formatter
  - branch-api
  - cloudbees-folder
  - credentials
  - durable-task
  - git
  - git-client
  - git-server
  - github-api
  - github-oauth
  - handlebars
  - icon-shim
  - jquery-detached
  - junit
  - mailer
  - matrix-auth
  - matrix-project
  - momentjs
  - pipeline-build-step
  - pipeline-input-step
  - pipeline-rest-api
  - pipeline-stage-step
  - pipeline-stage-view
  - scm-api
  - script-security
  - ssh-credentials
  - structs
  - windows-slaves
  - workflow-aggregator
  - workflow-api
  - workflow-basic-steps
  - workflow-cps
  - workflow-cps-global-lib
  - workflow-durable-task-step
  - workflow-job
  - workflow-multibranch
  - workflow-scm-step
  - workflow-step-api
  - workflow-support

