# -*-ruby-*-

VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.8"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.ssh.insert_key = false

    config.vm.provider 'virtualbox' do |v|
        v.linked_clone = true 
        v.cpus = 2
    end

    config.vm.box = "fedora/23-cloud-base" 
    config.vm.box_check_update = true
    config.vm.network "private_network", ip: "10.11.12.13"
    config.vm.synced_folder ".", "/vagrant", disabled: true

    # http://docs.ansible.com/ansible/guide_vagrant.html
    config.vm.provision "ansible" do |ansible|
        ansible.limit = "all"
        ansible.inventory_path = "./vagrant_hosts"
        ansible.verbose = "v"
        ansible.playbook = "../radia.yml"
    end
end

