# -*-ruby-*-

$script = <<SCRIPT
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.provider 'virtualbox' do |v|
        v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
    end

    config.vm.box = "fedora/23-cloud-base" 
    config.vm.box_check_update = true
    config.vm.hostname = "radiant"
    config.vm.provision "shell", inline: $script
end

