variable "channel" {}
variable "nat_gateway_id" {}
variable "subnet_cidr" {}
variable "vpc_id" {}
variable "bastion_security_group_id" {}
variable "worker_ami_id" {}
variable "worker_instance_type" {}
variable "ssh_key_name" {}
variable "worker_count" {}
variable "bastion_public_ip" {}
variable "ssh_private_key" {}
