---
mpi_cluster:
  ssh2_algos:
    - ecdsa
    - ed25519
    - rsa
  worker:
    image_name: 'radiasoft/beamsim-jupyter:{{ rs_channel }}'
    sshd_port: 2200
    guest:
      ssh_conf_d: /home/vagrant/.ssh
      sshd_conf_d: /etc/ssh
    host:
      ssh_conf_d: /var/lib/mpi_worker/ssh
      sshd_conf_d: /var/lib/mpi_worker/sshd
    nfs_imports:
      mpi_cluster:
        #host: null
        names:
          - notebook
          - scratch  

mpi_cluster_worker_containers:
  containers:
    - command: "{{ mpi_cluster.worker.guest.sshd_conf_d }}/_sshd.sh" 
      image_name: "{{ mpi_cluster.worker.image_name }}"
      name: mpi_worker
      on_boot: yes
      service_state: started
      use_host_net: yes
      user: vagrant
      ports:
        - "{{ mpi_cluster.worker.sshd_port }}:{{ mpi_cluster.worker.sshd_port }}"
      volumes:
        - "{{ mpi_cluster.worker.host.ssh_conf_d }}:{{ mpi_cluster.worker.guest.ssh_conf_d }}"
        - "{{ mpi_cluster.worker.host.sshd_conf_d }}:{{ mpi_cluster.worker.guest.sshd_conf_d }}"

mpi_cluster_worker_firewall:
  ports:
    open:
      - "{{ mpi_cluster.worker.sshd_port }}/tcp"

