---
- name: disable selinux
  selinux: state=disabled

- name: root password
  user: name=root password="{{ root_md5 }}"
  when: root_md5

- name: vagrant group exists
  group: name=vagrant gid=1000 state=present system=no

- name: vagrant user exists
  user: name=vagrant uid=1000 group=vagrant state=present system=no

#TODO(robnagler) Only modify file if actually changes values;
# * Rename atomically
# * Validate temp file on target with a syntax checker if available
- name: turn off sudoers requiretty
  shell: "perl -pi.bak -e 's/^(?=Defaults\s+requiretty)/#/' /etc/sudoers"

- name: set hostname statically
  shell: hostnamectl set-hostname {{ inventory_hostname }} --static

- name: secure sshd_config
  shell: "perl -pi.bak -e 's/^#(PermitRootLogin)\s+yes/$1 without-password/;s/^(PasswordAuthentication)\s+yes/$1 no/' /etc/ssh/sshd_config"
