---
dependencies:
  - rs_global_defaults
  - rs_vars
  - rs_base
  - firewall
{% if rs_role == mpi_cluster_coordinator %}
  - role: nfs_server
    nfs_exports: "{{ mpi_cluster.coordinator.nfs_exports }}"
{% endif %}
{% if rs_role == mpi_cluster_worker %}
  - role: nfs_client
    nfs_imports: "{{ mpi_cluster.worker.nfs_imports }}"
{% endif %}
  - mpi_cluster
  - role: rs_containers
    rs_containers: "{{ mpi_cluster_coordinator_containers }}"
  - role: rs_nginx_proxy
    rs_nginx_proxy: "{{ mpi_cluster_coordinator_proxy }}"
