---
docker_manage_iptables: no
docker_service_d: "/etc/systemd/system/{{ docker_service_name }}.d"
docker_service_name: docker.service
docker_tls_options: ''
os_ver_d: "{{ ansible_distribution }}/{{ ansible_distribution_major_version }}"
sysconfig_d: /etc/sysconfig
