---
- name: create jupyter dirs
  file:
    group: vagrant
    mode: 0750
    owner: vagrant
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ mpi_cluster.coordinator.host.jupyter_conf_d }}"

- name: create jupyter notebook configuration
  template:
    dest: "{{ mpi_cluster.coordinator.host.jupyter_conf_d }}/jupyter_notebook_config.py"
    group: vagrant
    mode: 0640
    owner: vagrant
    src: jupyter_notebook_config.py.jinja
