---
dependencies:
  - role: jdauphant.ssl-certs
    ssl_certs_common_name: "{{ jenkins_domain }}"
    ssl_certs_path: /etc/ssl/star.radiasoft.org  
    ssl_certs_cert_path: /etc/ssl/star.radiasoft.org/star.radiasoft.org.crt  
    ssl_certs_privkey_path: /etc/ssl/star.radiasoft.org/star.radiasoft.org.key  
    ssl_certs_path_owner: root
    ssl_certs_path_group: nginx 
    when: deploy_env == "vagrant" 

  - role: radiasoft_ssl
    when: deploy_env != "vagrant"

  - role: jdauphant.nginx
    nginx_user: nginx
    nginx_events_params:
      - use epoll
      - multi_accept on   

    nginx_sites:
      jenkins_redirect:
        - |
            listen 80;
            server_name {{ jenkins_domain }};
            access_log  /var/log/nginx/jenkins.access.log;
            error_log  /var/log/nginx/jenkins.error.log;
            return 301 https://$host$request_uri;

      jenkins: 
        - | 
            listen 443 ssl;
            server_name {{ jenkins_domain }};
            access_log  /var/log/nginx/jenkins.access.log;
            error_log  /var/log/nginx/jenkins.error.log;

            ssl_certificate     /etc/ssl/star.radiasoft.org/star.radiasoft.org.crt;
            ssl_certificate_key /etc/ssl/star.radiasoft.org/star.radiasoft.org.key;
            
            location / {
                proxy_set_header        Host $host:$server_port;
                proxy_set_header        X-Real-IP $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Proto $scheme;
                proxy_redirect          http://     https://;
                proxy_pass              http://127.0.0.1:8080; 
                proxy_read_timeout      90;
            }

  - role: jenkins_pre

  - role: docker_deploy 
    container_name: jenkins
    image_name: docker.io/jenkins:latest
    docker_user: "{{ jenkins_host_user.uid }}:{{ jenkins_host_user.group }}" 
    docker_volumes: "{{ jenkins_home }}:/var/jenkins_home" 
    docker_ports: ["8080:8080", "50000:50000"]
    docker_env:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

