---
- package: name=nss-mdns state=present
  register: avahi_installed
- systemd: name=avahi-daemon daemon_reload=yes
  when: avahi_installed|changed
- systemd: name=avahi-daemon enabled=yes state=started
