---
- name: create firewall zones
  template:
    dest: "/etc/firewalld/zones/{{ item }}.xml"
    mode: 0440
    owner: root
    src: "{{ item }}.xml.jinja"
  notify:
    - restart firewalld
  with_items:
    - dmz
    - public
    - trusted
