---
- name: create firewall zones
  template:
    dest: "/etc/firewalld/zones/{{ item }}.xml"
    mode: 0440
    owner: root
    dest: "{{ item }}.xml.jinja"
  with_items:
    - internal
    - public
    - trusted
