---
- name: install docker repo gpg key
  rpm_key: state=present key=https://yum.dockerproject.org/gpg
- name: install docker repo conf
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo owner=root group=root mode=0644
- name: install docker requirements
  dnf: name={{ item }} state=present
  with_items:
    - docker-engine
    - python-docker-py  
- name: enable docker service
  systemd: name=docker.service enabled=yes state=started
