---
# This defines the configuration tree for the rs_containers role
# This tree encodes internal knowledge about how the containers should be configured
# and it is meant as invocation parameter for rs_containers. The information that
# it encodes is meant to be private.
rs_containers:
  want_docker_sock: yes
  containers:
    jupyterhub:
      command: "jupyterhub -f {{ jupyterhub.guest.conf_d }}/jupyterhub_config.py"
      image_name: "{{ jupyterhub.image_name }}"
      on_boot: yes
      service_state: started
      user: "{{ jupyterhub.host.user }}"
      ports:
        - "{{ jupyterhub.host.port }}:{{ jupyterhub.guest.port }}"
      volumes:
        - "{{ jupyterhub.host.conf_d }}:{{ jupyterhub.guest.conf_d }}"
        - "{{ jupyterhub.host.notebook_d }}:{{ jupyterhub.guest.notebook_d }}"
        - "{{ jupyterhub.host.scratch_d }}:{{ jupyterhub.guest.scratch_d }}"

    jupyter:
      image_name: "{{ jupyterhub.jupyter.image_name }}"
      state: absent
