---
- name: create ansible facts directory
  file: path=/etc/ansible/facts.d state=directory recurse=yes owner=root group=root mode=0755
- name: set deploy enviroment file
  template: src=deploy_env.j2 dest=/etc/ansible/facts.d/deploy_env.fact
