---
- name: add jenkins to docker group
  user: 
    name: "{{ jenkins_username }}"
    groups: jenkins,docker
    state: present  

- dnf: name={{ item }} state=present
  with_items:
    - policycoreutils-python-utils
    - java-1.8.0-openjdk-headless
    - wget  
      
- include: plugins.yml

- shell: /bin/wget https://{{ jenkins_domain }} || true
  when: ansible_local.deploy_env is not defined or ansible_local.deploy_env != "vagrant"
  args:
    creates: /root/jenkins.pp
    warn: no  

- shell: /bin/wget --no-check-certificate https://{{ jenkins_domain }} || true
  when: ansible_local.deploy_env is defined and ansible_local.deploy_env == "vagrant" 
  args:
    creates: /root/jenkins.pp
    warn: no  

# TODO: is there a better way to manage SELinux exceptions, so nginx can proxy from 80->8080?    
- shell: cat /var/log/audit/audit.log | grep nginx | grep denied | grep 'dest=8080' | audit2allow -M jenkins
  register: jenkins_semodule    
  args:
    creates: /root/jenkins.pp

- command: /sbin/semodule -i /root/jenkins.pp
  when: jenkins_semodule|changed


