---
- dnf: name={{ item }} state=present
  with_items:
    - policycoreutils-python-utils
    - java-1.8.0-openjdk-headless
    - wget  
      
- include: plugins.yml

- shell: wget https://{{ jenkins_domain }} || true
  when: deploy_env != "vagrant"
  register: jenkins_semodule    
  args:
    creates: /root/jenkins.pp

- shell: wget --no-check-certificate https://{{ jenkins_domain }} || true
  when: deploy_env == "vagrant"
  register: jenkins_semodule    
  args:
    creates: /root/jenkins.pp

- shell: cat /var/log/audit/audit.log | grep nginx | grep denied | grep 'dest=8080' | audit2allow -M jenkins
  register: jenkins_semodule    
  args:
    creates: /root/jenkins.pp

- command: /sbin/semodule
  register: jenkins_semodule    
  args:
    chdir: /root
    creates: /root/jenkins.pp

- command: /sbin/semodule -i /root/jenkins.pp
  when: jenkins_semodule|changed


