---
docker_service_name: docker.service
docker_service_d: "/etc/systemd/system/{{ docker_service_name }}.d"
docker_tls_options: ''
sysconfig_d: /etc/sysconfig
docker:
  dm:
    thinpool: thinpool
    volume_group: docker
    thinpooldev: /dev/mapper/docker-thinpool
