---
dependencies:
  - rs_global_defaults
  - rs_vars
  - rs_base
  - role: nfs_server
    nfs_exports: "{{ mpi_cluster.coordinator.nfs_exports }}"
  - mpi_cluster/coordinator/pre
  - role: rs_containers
    rs_containers: "{{ mpi_cluster_coordinator_containers }}"
  - role: rs_nginx_proxy
    rs_nginx_proxy: "{{ mpi_cluster_coordinator_proxy }}"
  - role: rs_firewall
    rs_firewall: "{{ mpi_cluster_coordinator_firewall }}"
