---
mpi_cluster:
  ssh_cmd: /usr/bin/ssh
  #worker_addresses: []
  coordinator:
    mpi_bin:
      host_d: /srv/jupyterhub/ssh
      dirname: bin 
    #user_name: null
    #user_password: null
  worker:
    sshd_port: 2200
  
rs_role: mpi_cluster_coordinator
