---
mpi_cluster:
  #worker_addresses: []
  coordinator:
    ssh:
      host_d: /srv/jupyterhub/ssh
      dirname: .ssh
    #user_name: null
    #user_password: null
  
rs_role: mpi_cluster_coordinator
