---
mpi_cluster:
  #worker_addresses: []
  coordinator:
    mpi_bin:
      host_d: /srv/jupyterhub/mpi_bin
      dirname: mpi_bin
    #user_name: null
    #user_password: null
  worker:
    sshd_port: 2200
  
rs_role: mpi_cluster_coordinator
