---
- name: set timezone to {{ timesync_tz }}
  timezone: name={{ timesync_tz }}
  register: tz

- name: ensure chrony is installed
  yum: name=chrony state=present
  register: chrony

- name: register chrony service
  systemd: name=chronyd.service enabled=yes state=started

- name: restart chrony service
  systemd: name=chronyd.service daemon_reload=yes state=restarted
  when: chrony|changed or tz|changed
