---
- name: create nginx directories
  file: state=directory path={{ item.p }} owner=root group=root mode={{ item.m }}
  with_items:
    - { p: "{{ nginx.auth_d }}", m: "0750" }
    - { p: "{{ nginx.conf_d }}", m: "0755" }
    - { p: /var/log/nginx, m: "0755" }
  loop_control:
    label: "{{ item.p }}"

- include: manage_proxy_entry.yml
  with_items: "{{ rs_nginx_proxy }}"
  loop_control:
    loop_var: proxy
