---
- name: nginx auth info for {{ proxy.name }}
  htpasswd:
    group: root
    mode: 0640
    name: "{{ item.key }}"
    owner: root
    password: "{{ item.value }}"
    path: "{{ nginx.auth_d }}/{{ proxy.name }}"
  with_dict: "{{ proxy.auth }}"
  when: proxy.auth is defined
  no_log: yes

- name: nginx config for {{ proxy.name }}
  template:
    dest: "{{ nginx.conf_d }}/{{ proxy.name }}.conf"
    group: root
    mode: 0640
    owner: root
    src: nginx_conf.jinja

