---
- name: fetch docker {{ image_name }} image
  docker_image: name={{ image_name }}
- name: start docker {{ image_name }} as {{ container_name }}
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    volumes: "{{ volumes | default(omit) }}"
    command: "{{ cmd | default(omit) }}"
    log_driver: journald
    tty: yes  
