---
- name: install docker repo gpg key
  rpm_key: state=present key=https://yum.dockerproject.org/gpg

- name: install docker repo conf
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo owner=root group=root mode=0644

- name: install docker requirements
  dnf: name={{ item }} state=present
  with_items:
    - docker-engine
    - python-docker-py  

- name: enable docker service
  systemd: name=docker.service enabled=yes state=started

- name: fetch docker {{ image_name }} image
  docker_image: name={{ image_name }}
  when: not image_name|includes(':')

  # TODO: Test when ansible 2.2.0 is released
# https://github.com/ansible/ansible-modules-core/issues/3719
# https://github.com/ansible/ansible/pull/16680
- name: fetch docker {{ image_name }} image with tag (workaround)
  command: "{{ docker_path }} pull {{ image_name }}"
  when: image_name|includes(':')

- name: create container {{ container_name }} from {{ image_name }} 
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    volumes: "{{ docker_volumes | default(omit) }}"
    command: "{{ cmd | default(omit) }}"
    user: "{{ docker_user | default(omit) }}"  
    log_driver: journald
    tty: yes  
    published_ports: "{{ docker_ports | default(omit) }}" 
    env: "{{ docker_env | default(omit) }}"
    state: present  

- name: create systemd service for {{ container_name }}
  template: src=systemd.j2 dest=/etc/systemd/system/{{ container_name }}.service owner=root group=root mode=0644
    
- systemd: name={{ container_name }} state=started enabled=yes daemon_reload=yes
