---
- name: install utility packages
  package: name={{ item }} state=present
  with_items:
    - bind-utils
    - emacs-nox
    - htop
    - iftop  
    - iotop  
    - lsof
    - openssl
    - screen
    - strace  
    - tar
    - tcpdump
    - telnet
    - the_silver_searcher 
    - tmux
    - vim-enhanced

- name: screenrc configuration
  blockinfile: 
    dest: /etc/screenrc
    insertafter: EOF
    block: "escape ^^^^"
