---
nginx_conf_d: /etc/nginx/conf.d
nginx_proxy_container:
  containers:
    - image_name: nginx
      name: nginx_proxy
      on_boot: yes
      service_state: started
      ports:
        - 80:80
        - 443:443
      volumes:
        - "/var/log/nginx:/var/log/nginx"  
        - "{{ nginx_conf_d }}:{{ nginx_conf_d }}"  
        - "{{ ssl_storage.certs }}:{{ ssl_storage.certs }}" 
        - "{{ ssl_storage.private }}:{{ ssl_storage.private }}"
