---
nginx:
  auth_d: /etc/nginx/auth.d
  conf_d: /etc/nginx/conf.d

nginx_proxy_container:
  containers:
    - image_name: nginx
      name: nginx_proxy
      on_boot: yes
      service_state: started
      volumes:
        - "/var/log/nginx:/var/log/nginx"
        - "{{ nginx.auth_d }}:{{ nginx.auth_d }}"
        - "{{ nginx.conf_d }}:{{ nginx.conf_d }}"
        - "{{ ssl_storage.certs }}:{{ ssl_storage.certs }}"
        - "{{ ssl_storage.private }}:{{ ssl_storage.private }}"
