---
- name: install nfs packages
  package: name={{ item }} state=installed
  with_items:
    - nfs-utils
    - rpcbind  

- name: enable nfs services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - rpcbind
    - nfs-server

- include: search_nfs_host.yml
  with_dict: '{{ hostvars }}'

- include: manage_import.yml
  with_items: '{{ imports }}' 
  loop_control: 
    loop_var: import_group
