---
- name: create imported mount point
  file: path={{ nfs_import_prefix }}/{{ import_group.key }}/{{ item }} state=directory
  with_items: "{{ import_group.value.names }}"
  loop_control:
    label: "{{ import_group.value.host }}:{{ import_group.key }}/{{ item }}"

- name: mount nfs imports
  mount:
    fstype: nfs
    name: "{{ nfs_import_prefix }}/{{ import_group.key }}/{{ item }}"
    src: "{{ import_group.value.host }}:{{ nfs_export_prefix }}/{{ import_group.key }}/{{ item }}" 
    state: mounted 
  with_items: "{{ import_group.value.names }}"
  loop_control:
    label: "{{ import_group.value.host }}:{{ import_group.key }}/{{ item }}"
