---
nfs_exports:
  jupyterhub:
    - group: 1000
      name: notebook
      nfs_config: '*(rw,insecure,no_root_squash,no_subtree_check,sync,fsid=5000)'
      owner: 1000

    - group: 1000
      name: scratch
      nfs_config: '*(rw,insecure,no_root_squash,no_subtree_check,sync,fsid=5001)'
      owner: 1000
