---
- name: install package requirements
  dnf: name={{ item }} state=present
  with_items:
    - firewalld
    - python-firewall 
- name: firewall running
  systemd: name=firewalld state=started enabled=yes daemon_reload=yes
- name: host conf.d
  file: state=directory path={{ sonos.host_conf_d }} owner=root group=root mode=0644
- name: settings
  template: src=settings.j2 dest={{ sonos.host_settings_json }} owner=root group=root mode=0640
- name: presets
  copy: src=presets.json dest={{ sonos.host_presets_json }} owner=root group=root mode=0644
- name: firewall settings
  template: src=firewall.j2 dest=/etc/firewalld/services/sonos.xml owner=root group=root mode=0644
  notify:
    - reload firewall
    - restart firewall  
